### ISSUE TITLE
App crashes if line 31 of InitViewController.swift is not comment out first

### ISSUE THREAD

**Issue by clay53** [lbryio/odysee-ios#1]
On the first run of the app, line 31 of InitViewConttroller.swift must be commented out (`print("********" + Lbryio.authToken!`) as it will cause a `Fatal error: Unexpectedly found nil while unwrapping and Optional value`. This happens because on the first run, "AuthToken" has not yet been added to UserDefaults. If this line is commented out, the app runs fine and the line can then be added back as "AuthToken" will have been added to UserDefaults.

**Comment by kauffj** [comment]
Congratulations on creating the first odysee-ios issue! How do you feel about going for first odysee-ios community contribution? 😀

**Comment by clay53** [comment]
> Congratulations on creating the first odysee-ios issue! How do you feel about going for first odysee-ios community contribution?
I think that'd be neat

**Comment by akinwale** [comment]
Hey, thanks for the report, but this is mostly debug code which will ultimately be removed.
