### ISSUE TITLE
Sound stops playing when skipping into video

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/odysee-ios#102]
A user reported this last week while using headphones, and got more complaints today and I was also able to see it on https://odysee.com/@DollarVigilante:b/Covaids-1984-and-the-Kill-Gates-Globalist-Dictatorship:b . It happens if you skip forward into the video, but it's fine if you just let it play.

**Comment by tzarebczan** [comment]
What's strange is that this also happens on Safari odysee.com also. Will try to do more testing to see if it's certain videos or not.

**Comment by akinwale** [comment]
Haven't been able to find a solution for this yet. Maybe it has something to do with the video / audio encoding? Is this reproducible with other videos?

**Comment by tzarebczan** [comment]
Bret ran into this over the weekend so we'll need to take another look. Do think it's something with encoding as it went away after being transcoded. 

I'll get the original file uploaded so we can test more.

**Comment by tzarebczan** [comment]
Found another video with a similar issue, which was not mono as Bret's was. The other common factor was 48khz, but I could not repro this is a different sample file. 

https://odysee.com/@AlexJonesChannel:c/Joe-Biden-Praises-China-While-Fake-Driving-An-Electric-Truck-At-Ford-Plant:2 is non transcoded, with same issue.

transcoded: 
https://odysee.com/@AlexJonesChannel:c/Black-Rifle-Coffee-Company-Declares-War-on-America:f 

Akin/Andrey both aware.
