### ISSUE TITLE
Re-do first run to more strongly encourage verification and channel creation and use manual verification endpoints

### ISSUE THREAD

**Issue by kauffj** [lbryio/odysee-ios#111]
The endpoints for manual verification may not all exist. @e4drcf will provide details.

**Comment by kauffj** [comment]
https://github.com/lbryio/lbry-verification.go/pull/4/files

**Comment by kauffj** [comment]
This is workable

**Comment by akinwale** [comment]
Closing in favour of https://github.com/lbryio/odysee-ios/issues/188.
