### ISSUE TITLE
Two live AVPlayerViewController instances per FileViewController

### ISSUE THREAD

**Issue by Adlai-Holler** [lbryio/odysee-ios#114]
Very exciting project! `FileViewController` has the following code chunk in both `viewDidLoad` and `viewDidAppear`:

```swift
displayClaim()
loadAndDisplayViewCount()
loadReactions()
loadRelatedContent()
loadComments()
```

There's a lot of duplicated work triggered by this when displaying FileVC, but most likely the biggest is that we end up getting two return callbacks to `initializePlayerWithUrl` and instantiating two `AVPlayerViewControllers` and adding them both to the hierarchy. The previous instance is perma-paused, but still in memory and in the view hierarchy.

<img width="845" alt="Screen Shot 2021-05-17 at 7 12 38 PM" src="https://user-images.githubusercontent.com/2466893/118567667-35034d00-b744-11eb-81b3-b2510ffc02ba.png">

`viewDidLoad` is probably the best time to do UI and hierarchy modifications like this, because it'll be before the first layout pass for that view.

**Comment by tzarebczan** [comment]
Thanks so much for opening this issue! Would you care to take a shot at fixing it, or want to leave it unclaimed? 

Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the report?

**Comment by Adlai-Holler** [comment]
Sure I'd love to take a shot at fixing it. Next up for me is #119 though. I can get to this hopefully in the next few days.

I just sent an email to hello@lbry.com with my LBC address – appreciation is always welcome! 😎
