### ISSUE TITLE
Upload flow should not load video file into memory

### ISSUE THREAD

**Issue by Adlai-Holler** [lbryio/odysee-ios#126]
Right now the upload code uses an `NSMutableData` to form the entire multipart upload data into one big data blob. This means using `Data(contentsOf: videoUrl)`. Since video files are pretty big, this is not ideal. We should leave it on disk, and tell iOS to stream the data as-needed.

A better approach would be using the [`URLRequest.httpBodyStream`](https://developer.apple.com/documentation/foundation/nsurlrequest/1407341-httpbodystream) property. We need to form the body stream from 3 parts:

- A stream containing the `Data` before the video file
- A stream of the video file from disk, i.e. `InputStream(url: videoUrl)`
- A stream containing the `Data` after the video file

There's an Objective-C helper class [here](https://github.com/couchbaselabs/TouchDB-iOS/blob/master/Source/TDMultiStreamWriter.h) that can combine streams like this, so we need to either import that directly, or make a stripped-down clone of it in Swift.

I think I can get this done.

**Comment by akinwale** [comment]
A direct import is fine if the license is compatible with MIT, or any similar open source licenses.
