### ISSUE TITLE
Consistent crash when trying to play 1st video from Following tab

### ISSUE THREAD

**Issue by robd003** [lbryio/odysee-ios#153]
I've had a consistent crash on a specific video that was published 2 hours ago. It works fine on the website, but if using the iOS app it'll totally crash the app.

[Video that's crashing](https://odysee.com/@SaltyCracker:a/katie-hill-sex-pics-lawsuit-backfires:b)

I've attached the crash log from iOS. Let me know if there's any other info you'd need.
[Odysee-2021-06-03-112505.ips.txt](https://github.com/lbryio/odysee-ios/files/6592737/Odysee-2021-06-03-112505.ips.txt)

This was happening on the official release 0.4.2 from the App Store

**Comment by robd003** [comment]
Just tried running from the TestFlight beta and the video played just fine. I'll update the ticket if I see any other crashes in 0.4.3

**Comment by akinwale** [comment]
Closing this. Please reopen this ticket if you encounter the same crash again.
