### ISSUE TITLE
New users can't comment - verification/LBC problem

### ISSUE THREAD

**Issue by julianchandra** [lbryio/odysee-ios#188]
Problems:
New users (mainly weinstein fans) join through iOS and watch videos through either the browser or app. They go to comment and discover that they can't because there's no channel associated with the user account.
The 'channel' menu item under the avatar button isn't being understood by a user and doesn't carry the same meaning as 'profile set up' for them. 
Once they're directed to the 'channel' page to set up their channel/profile in order to comment they can't actually save the details they input because they have no LBC. 
They therefore can't comment/engage with content.

This impacts any user who creates an account through iOS. All they can do is watch videos.

Side question: If the ability to comment is being tied to verification does this mean only users that verify their accounts can comment? 

![issue](https://user-images.githubusercontent.com/67612037/123560856-f78ce780-d7f8-11eb-8707-49e2abaaf9f7.png)

**Comment by kauffj** [comment]
Examine first-run as well. If we can get profile setup to happen during first run, this issue is diminished.

**Comment by akinwale** [comment]
Made a few tweaks
* Added a call to action to the comment view to allow users go directly to the channel creation page.
* The app will try to repeatedly claim the email verified reward until the request is successful, as opposed to the initial implementation where it was only attempted once.
* Fixed the channels view to display a New Channel option when there are no channels.
