### ISSUE TITLE
Sorry not sure where else to put this: 

### ISSUE THREAD

**Issue by PeterKW** [lbryio/odysee-ios#191]
Are there github projects to follow somewhere on https://github.com/lbryio for the progresses of Odysee for Android & Linux? Sorry, couldn't track down more information about this.

**Comment by akinwale** [comment]
We will set up a repository for odysee-android soon.

**Comment by PeterKW** [comment]
Are there any updates to this @akinwale? I would be happy to contribute code to it

**Comment by tzarebczan** [comment]
It's still private, will be made public in the next week or two.
