### ISSUE TITLE
iPad Support

### ISSUE THREAD

**Issue by MeneerGroot** [lbryio/odysee-ios#216]
There is no iPad support. The app on iPad is a iPhone screen size that's being blown up.

**Comment by MeneerGroot** [comment]
![image](https://user-images.githubusercontent.com/53813521/125699259-b08e75ef-b602-494b-af24-b9d620e7cb24.png)

**Comment by MeneerGroot** [comment]
![image](https://user-images.githubusercontent.com/53813521/125699276-93ed7952-39d7-4431-a112-7b257b58101b.png)

**Comment by tzarebczan** [comment]
thanks for opening, this is a duplicate of https://github.com/lbryio/odysee-ios/issues/6
