### ISSUE TITLE
Text posts have the iOS video loading screen indefinitely

### ISSUE THREAD

**Issue by eatdostacos** [lbryio/odysee-ios#22]
I tried opening a text post and it doesn't load the text. It looks like a video with the loading icon spinning.

**Comment by tzarebczan** [comment]
How did you get to the text post?

**Comment by eatdostacos** [comment]
> How did you get to the text post?

I went to the channel with the post and then I scrolled down and clicked on the post.

**Comment by akinwale** [comment]
Text posts are not yet supported, but they will be in a later version.

**Comment by akinwale** [comment]
Closing in favour of https://github.com/lbryio/odysee-ios/issues/104.
