### ISSUE TITLE
wild west broken

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/odysee-ios#228]
on odysee.com, we only show the default trending sort

don't think the sort method changes anything

wild west should not pass any channels, should be wide open (I see common channels only)

**Comment by akinwale** [comment]
We've been using the primary channels for Wild West on iOS from the beginning. Will fix.

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/odysee-ios/commit/ab9fcf1773ecb9bc49235d1e829a9e7e0fa329aa.
