### ISSUE TITLE
Support < iOS14

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/odysee-ios#25]
Have gotten a few complaints/requests for this. What would it take?

**Comment by akinwale** [comment]
Would require some testing on iOS 13 devices. Also, WebP thumbnails will not display.

**Comment by robster7674** [comment]
Sign me up for testing! ;) It would be great to be able to get the app running on some older devices as well (iOS 12 on iPhone 6), as not all of us have the money to keep up with Apple's device refresh cycles. But let's do iOS 13 first.

**Comment by robster7674** [comment]
Hi @akinwale , is there any progress on this yet? I don't want to upgrade my iPhone to iOS 14, and my older devices cannot be upgraded.

**Comment by Adlai-Holler** [comment]
WebP thumbnails will now work since we've switched to PINRemoteImage.

**Comment by Adlai-Holler** [comment]
I can take this task on.
