### ISSUE TITLE
keeps looping into "retrieving account data" 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/odysee-ios#30]
https://twitter.com/Barnacules/status/1360122218328457217

**Comment by tzarebczan** [comment]
Got a few more complaints of this, from various pages.

**Comment by tzarebczan** [comment]
https://i.gyazo.com/8c0d6c6d230f4b075cc56360d6291051.gif

**Comment by akinwale** [comment]
I've added some additional checks to prevent this condition. If it happens again, please reopen this ticket.
