### ISSUE TITLE
notification improvements and bugs

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/odysee-ios#37]
bugs:
- [x] first load came up with no notifications, took a while to show empty state.
- [x] clicking on a content notification doesn't take you to the content - takes you to the channel and it shows "no content to display". Same thing happens with device notifications that have : lbry://@timcast#c9/gop-reps-family-disowns-him-for#4 as target
- [x] pass is_app_readable param to notification list
- [x] new comments show "in 4 hours" - looks like timezone / UTC is off.
- [x] don't think the notification pull-down refreshes them...I had to leave and come back to the page to see new ones. 
 
improvements:
- [x] show channel thumbnail of commenter/replies
- [ ] show thumbnail of content

I'm working on a PR to add this right into all notification metadata so we don't have to resolve it.

**Comment by tzarebczan** [comment]
Refreshing and timezone issue is super annoying... Had to close and re-open the app to get a new notification, so don't think WS is working either.

**Comment by akinwale** [comment]
Fixed the timezone and refresh issues.
