### ISSUE TITLE
Odysee iOS app Testing

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/odysee-ios#4]
@julianchandra commented on [Thu Jan 14 2021](https://github.com/lbryio/odysee-homepages/issues/45)

- [ ] **1. Sign up Flow issue** - Critical
 If I sign up through mobile, I get the email verification, it opens the browser and I'm in Odysee on web.
But my mobile app doesn't do anything. 

- [ ] **Community guidelines + link to the help/support for Apple compliance** - Critical (no app allowed without this)
@tzarebczan we used to have a custom odysee contact/support page but it appears to be missing (redirects to lbry now).
If we can bring that back it might make things easier?
The user needs to be able to submit support requests through app (if needs to open your inbox that's ok) - mandatory.

**To test:**

- [ ] Signing in and out (can't sign out once in)
- [x] Fire a video
- [x] Slime a video
- [ ] Leave a comment (doesn't work)
- [ ] Fire a comment (can't)
- [ ] Slime a comment (can't)
- [x] Follow a channel
- [ ] Unfollow a channel (doesn't work)
- [x] Tip a video
- [x] Tip a channel

**Missing features (for awareness - not necessarily mandatory right away, though profile/settings might be good to have):**

- [ ] Can't sync YT channel through sign up - so only end users can join through app, not creators
- [ ] Can't upload
- [ ] Can't access creator analytics
- [ ] Can't access profile/settings

---

@julianchandra commented on [Thu Jan 14 2021](https://github.com/lbryio/odysee-homepages/issues/45#issuecomment-759975872)

**Bugs**

- [ ] I unfollowed a channel and it was still showing in my following even though in the channel profile it shows i'm not following them.

- [ ] Gaming category won't load

- [ ] Can't sign out once in.

- [ ] Can't close the keyboard once open on a video page. 
You need to go out of it and back to close it.
![IMG-0510](https://user-images.githubusercontent.com/67612037/104556584-bff40e00-56a4-11eb-829c-1d1dc73b12cb.PNG)

- [ ] Seems impossible to scroll down to comments on certain videos because of too many related videos.
![IMG-0513](https://user-images.githubusercontent.com/67612037/104556630-cedac080-56a4-11eb-9f59-33ffd780735e.PNG)

- [ ]  Sometimes fire/slime etc are missing from below the video.
![IMG-0513](https://user-images.githubusercontent.com/67612037/104556644-d5693800-56a4-11eb-9143-9772d44b9ddd.PNG)

- [ ] Longer comments appear cropped, it's not clear if there are multiple comments or just one. I recommend we copy YT and put comments at the top below the fire/slime etc. Will attach the example of the issue and then the YT suggestion.
![comments weird](https://user-images.githubusercontent.com/67612037/104557085-8374e200-56a5-11eb-992d-006a2f90669f.png)

YOUTUBE example:
![IMG-0512](https://user-images.githubusercontent.com/67612037/104557111-8c65b380-56a5-11eb-8d2f-3d65d662add6.PNG)

**Design inconsistency - not a bug**
- [ ] The avatar appears to be cropped differently from the normal circular shape.
![IMG-0514](https://user-images.githubusercontent.com/67612037/104556703-efa31600-56a4-11eb-9475-5d6b2c7a22b7.PNG)

**Comment by akinwale** [comment]
Duplicate.
