### ISSUE TITLE
Account >Channels page goes to channel edit

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/odysee-ios#43]
```There is no way in the iOS app to view my channel other than to manually search for it. Selecting channels from the top-right nav puts you directly into "edit channel" where (in my eyes) it should display my channel(s) with an additional option to edit them. Hope this helps. 🙏```

**Comment by akinwale** [comment]
Done in https://github.com/lbryio/odysee-ios/commit/77d48bbdc1dca1486d82cceb7a5ba75142e5e5e6. You can now tap to view your own channel and long-press to edit.

**Comment by tzarebczan** [comment]
Looks like you did the opposite - long press > goes to view. clicking > edit.

**Comment by akinwale** [comment]
Yes, this is intentional. The primary action for the channels list view is meant to be Edit, since there is an arrow decoration which indicates that's what it's meant for, following design guidelines. Long-press lets you view the channel.
