### ISSUE TITLE
video goes blank after landscape + control center

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/odysee-ios#54]
https://twitter.com/JacobTalksTech/status/1367516870467674112

**Comment by tzarebczan** [comment]
Videos go black anytime when pulling down to check notifications. Play button shows, but it's blank and still palying. We should fix this asap.

**Comment by akinwale** [comment]
Fixed in https://github.com/lbryio/odysee-ios/commit/6f75b1d2796a42c0a5e54f1a5130b5d1e31d1dba.
