### ISSUE TITLE
youtube sign up issues - keyboard takes over, can't continue

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/odysee-ios#55]
When registering to your site/app, we are quickly led to a sync youtube channel stage.

At this stage, the keyboard blocks half the screen and there is no way to validate input and go forward. Only solution is to force the app closed.

I'm on iPhone SE 2020 and I am running latest OS.
![image](https://user-images.githubusercontent.com/8120721/110144844-c8b0b880-7da6-11eb-9eb2-aa7436ca56ae.png)
![image](https://user-images.githubusercontent.com/8120721/110144850-cbaba900-7da6-11eb-9a33-dabe70fc7490.png)

**Comment by akinwale** [comment]
Fixed to allow scrolling when the soft keyboard is displayed.
