### ISSUE TITLE
Subscriptions thumbnails duplication 

### ISSUE THREAD

**Issue by anohren** [lbryio/odysee-ios#65]
On the Following tab, two of my three subscriptions regularly get identical thumbnail images in the channel list at the top. One correct, one wrong. 

While I didn't immediately notice any cell reuse issues by inspecting the collection view, I'm not ruling it out. Without being familiar with the code I'd guess a more likely cause would be that the network responses are assumed to be ordered but aren't handled in strict order, or that item indices are reused in some callback/aren't properly looked up at the time of receiving a response.

**Comment by tzarebczan** [comment]
Thanks for filing. Are you seeing this after scrolling or on the main page load? If it's after scrolling, the new results are probably not handled properly in the case that there's shifting between pages.

**Comment by anohren** [comment]
I'm seeing this when loading the tab. No scrolling.

**Comment by akinwale** [comment]
This is fixed in the latest release.
