### ISSUE TITLE
Possibility to launch directly to the Following tab

### ISSUE THREAD

**Issue by anohren** [lbryio/odysee-ios#67]
For those of us who feel more at home on the Following tab than on the Home tab, it would be nice to be able to arrive directly to it upon launch (without having to use the appicon context menu). I would prefer not to see any arbitrary recommendations.

**Comment by kauffj** [comment]
@akinwale maybe the last tab you were on could be retained?

**Comment by anohren** [comment]
That's the most simple solution I could think of as well, requiring no new UI.
