### ISSUE TITLE
token/data not cleared when clicking "start over"  / other auth issues (the sign in bugs)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/odysee-ios#7]
I noticed when being forced to login to an account that required email login.

The flow:
enter email
get prompted for magic link sign in
click start over
retype same email - told to enter a password, can't continue

Need to leave the login page and go back to start the flow again.

**Comment by tzarebczan** [comment]
Some more related around the auth flow: 
![image](https://user-images.githubusercontent.com/8120721/114060501-70684d00-9863-11eb-93bb-31cbd03bb4fe.png)
![image](https://user-images.githubusercontent.com/8120721/114060512-752d0100-9863-11eb-84fd-3668076572ee.png)

**Comment by akinwale** [comment]
Auth token reset fixed in https://github.com/lbryio/odysee-ios/commit/2fa879f19968bc8bc0bfa125056f5c74d200f686. Other sign in / sign up issues were previously fixed.
