### ISSUE TITLE
Cannot skip some steps for new first run experience

### ISSUE THREAD

**Issue by JoshuaCrewe** [lbryio/odysee-ios#70]
Although this isn't actually my first run, I have been using the app for a few weeks, the app welcomes me with some on boarding. Setting a channel name for example.

Initially this was completely broken and I couldn't do anything, pick a channel name or skip. After updating to the latest version  (0.3.1) in the app store I get more options.

I can skip the channel name. I could skip whatever the second option was but I can't skip the Reward Verification page. The skip button in the bottom left doesn't do anything. I don't want to verify and can't use any of the options even if I did. When I quit the app I get launched into the verification screen.

I can't navigate the onboarding screen at all.

*What I did*
1. Launch the app (version 0.3.1)
2. Skip step one (choose a channel name)
3. Skip step two (I don't remember what this was and can't get back)
4. Skip verfication

*What happened*
I get stuck on the verification option with no option to skip or navigate backwards to previous steps

*what I expect to happen*
I expect to press the skip button and be free to use the app

iOS version : 14.4.1
Phone Model : iPhone 6s
Odysee version : 0.3.1

**Comment by tzarebczan** [comment]
This has been fixed in a patch, should be out any day. Sorry for the trouble!

**Comment by JoshuaCrewe** [comment]
No need to apologise! Keep up the good work, I really appreciate the effort :)
