### ISSUE TITLE
Search - Virtual keyboard is closing when search result is updated

### ISSUE THREAD

**Issue by robot3498712** [lbryio/odysee-ios#8]
Steps:
1. Open odysee app
2. Click search-button via header
3. Input valid search phrase sequentially using the virtual keyboard, for example: "die anstalt"
4. Observe while typing

Expected:
Focus remains on search input and keyboard is not closing.

Actual:
When the search result is updated, focus is lost and keyboard is closing. Most often one of the search results is clicked since I resumed typing. This is rather annoying and most unpleasant UX.

Env/Version:
Odysee 0.1.0 (via testflight) on iPhone 7/ios 14.4

**Comment by akinwale** [comment]
The timeout has been increased for the search input, so that the keyboard does not close while the user is still typing.
