### ISSUE TITLE
Usability issues around comments on smaller screens

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/odysee-ios#82]
- can't see comment being made or post button
https://d33v4339jhl8k0.cloudfront.net/inline/67942/cf4219222d1927d98fd671b98cb6bb0767fc018e/41b90bf39ce5c491abfe660a8d6018d31dee3759/image2.png

**Comment by tzarebczan** [comment]
This also affects other areas like error messages / UI feedback.

**Comment by tzarebczan** [comment]
![image](https://user-images.githubusercontent.com/8120721/116931534-17f05980-ac2f-11eb-88a7-9374df81de58.png)

**Comment by tzarebczan** [comment]
- [ ] on channel creation/edit, when you click into the lower fields, the keyboard covers the field

**Comment by akinwale** [comment]
> This also affects other areas like error messages / UI feedback.

Made some tweaks for this. Will push a test build up.

> on channel creation/edit, when you click into the lower fields, the keyboard covers the field

You should be able to scroll when the keyboard shows. Does this not happen?

**Comment by akinwale** [comment]
Fixed in latest test build.
