### ISSUE TITLE
AirPlay - streaming to Apple TV is interrupted, playback progress reset

### ISSUE THREAD

**Issue by robot3498712** [lbryio/odysee-ios#9]
Steps:
1. Open odysee app
2. Find a video via e.g. Following > Channel
3. Play video, then click the in-video - AirPlay - button
4. Stream to Apple TV (4k)
5. Click outside to hide AirPlay dialog, then leave the phone
6. Wait and watch for a while

Expected:
Uninterrupted playback on remote device.
In case of network issue loading animation is displayed, then the video eventually is resumed.
Playback progress is never reset.

Actual:
Quite often streaming stops abruptly (typically when/after iPhone screen has turned off, but not always).
Re-activating phone, progress has typically been reset (progress 0 seconds).

I've observed this behavior frequently over the past days. This may not be a (and certainly is not a local) networking issue; even if it is, behavior would be unexpected.

Env/Version:
Odysee 0.1.0 (via testflight) on iPhone 7/ios 14.4

**Comment by kauffj** [comment]
Using #51
