### ISSUE TITLE
Wrong video thumbnails, Following tab

### ISSUE THREAD

**Issue by anohren** [lbryio/odysee-ios#91]
Essentially the same as #65 but for video thumbnails:

Filtering the video list by tapping on a single channel and then quickly tapping again to view all videos results in the list of all videos getting video thumbnails from the previously selected channel. 

To me it suggests an incorrect reuse of old indices, and/or erroneously relying on a strict ordering of non-ordered async operations.

**Comment by akinwale** [comment]
This is fixed in the latest release.
